export const todayPickMoviesData = [
  { id: 1, image: 'https://i.namu.wiki/i/JoJX0cuRBfLvH0Xr4ptiGKMjgLxg20eycTsY6YxCTpnFfifOew3DqEk8CqjcHjT5XgYeCuoMcDxWQzIhIXr-5w.webp' },
  { id: 2, image: 'https://i.namu.wiki/i/jkXbUYN8qXanA4sO3jyMvBgS_l-mCr8cqdnii9ZTRHIQfX-cTVTM5ZY0bOfFHNBI5BQZq4XJjaheQI-kolj8vA.webp' },
  { id: 3, image: 'https://i.namu.wiki/i/29l8fINcGXd9do3-fjRx0C0zgb_nLDdT0XSZgQFKgRQBMMiEL6OsqouE8Apb3-7FXvMtQNklmQvi_--NL712Vw.webp' },
];
export const genres = [
  '액션',
  '모험',
  '애니메이션',
  '코미디',
  '범죄',
  '다큐멘터리',
  '드라마',
  '판타지',
  '역사',
  '공포',
  '음악',
  '미스터리',
  '로맨스',
  'SF',
  'TV 영화',
  '스릴러',
  '전쟁',
  '서부',
];
export const watchListData = [
    { image: 'https://via.placeholder.com/150', watchListTitle: '외국인을 위한 찐 한국인의 한국맛 영화 추천', heart: 50, listItem: 5 },
    { image: 'https://via.placeholder.com/150', watchListTitle: '외국인을 위한 찐 한국인의 한국맛 영화 추천', heart: 50, listItem: 5 },
    { image: 'https://via.placeholder.com/150', watchListTitle: '외국인을 위한 찐 한국인의 한국맛 영화 추천', heart: 50, listItem: 5 },
    { image: 'https://via.placeholder.com/150', watchListTitle: '외국인을 위한 찐 한국인의 한국맛 영화 추천', heart: 50, listItem: 5 },
    { image: 'https://via.placeholder.com/150', watchListTitle: '외국인을 위한 찐 한국인의 한국맛 영화 추천', heart: 50, listItem: 5 }
  ];
export const pickContentData = [
    {id:1,movieImage:'https://via.placeholder.com/150'},
    {id:2,movieImage:'https://via.placeholder.com/150'},
    {id:3,movieImage:'https://via.placeholder.com/150'},
    {id:4,movieImage:'https://via.placeholder.com/150'},
    {id:5,movieImage:'https://via.placeholder.com/150'},
    {id:6,movieImage:'https://via.placeholder.com/150'},
    {id:7,movieImage:'https://via.placeholder.com/150'},
    {id:8,movieImage:'https://via.placeholder.com/150'},
    {id:9,movieImage:'https://via.placeholder.com/150'},
    {id:10,movieImage:'https://via.placeholder.com/150'}
]
export const moviesData = [
  { title: 'Movie 1', imageUrl: 'https://via.placeholder.com/150', rating: 8.5, likes: 120, genre: '액션' },
  { title: 'Movie 2', imageUrl: 'https://via.placeholder.com/150', rating: 7.2, likes: 200, genre: '모험' },
  { title: 'Movie 3', imageUrl: 'https://via.placeholder.com/150', rating: 9.1, likes: 300, genre: '애니메이션' },
  { title: 'Movie 4', imageUrl: 'https://via.placeholder.com/150', rating: 6.8, likes: 150, genre: '코미디' },
  { title: 'Movie 5', imageUrl: 'https://via.placeholder.com/150', rating: 7.5, likes: 180, genre: '범죄' },
  { title: 'Movie 6', imageUrl: 'https://via.placeholder.com/150', rating: 8.0, likes: 220, genre: '다큐멘터리' },
  { title: 'Movie 7', imageUrl: 'https://via.placeholder.com/150', rating: 6.5, likes: 140, genre: '드라마' },
  { title: 'Movie 8', imageUrl: 'https://via.placeholder.com/150', rating: 7.8, likes: 210, genre: '판타지' },
  { title: 'Movie 9', imageUrl: 'https://via.placeholder.com/150', rating: 8.2, likes: 250, genre: '역사' },
  { title: 'Movie 10', imageUrl: 'https://via.placeholder.com/150', rating: 7.0, likes: 190, genre: '공포' },
  { title: 'Movie 11', imageUrl: 'https://via.placeholder.com/150', rating: 8.3, likes: 220, genre: '음악' },
  { title: 'Movie 12', imageUrl: 'https://via.placeholder.com/150', rating: 7.6, likes: 230, genre: '미스터리' },
  { title: 'Movie 13', imageUrl: 'https://via.placeholder.com/150', rating: 9.0, likes: 280, genre: '로맨스' },
  { title: 'Movie 14', imageUrl: 'https://via.placeholder.com/150', rating: 6.9, likes: 160, genre: 'SF' },
  { title: 'Movie 15', imageUrl: 'https://via.placeholder.com/150', rating: 7.9, likes: 250, genre: 'TV 영화' },
  { title: 'Movie 16', imageUrl: 'https://via.placeholder.com/150', rating: 8.7, likes: 300, genre: '스릴러' },
  { title: 'Movie 17', imageUrl: 'https://via.placeholder.com/150', rating: 6.4, likes: 130, genre: '전쟁' },
  { title: 'Movie 18', imageUrl: 'https://via.placeholder.com/150', rating: 8.4, likes: 210, genre: '서부' },
  { title: 'Movie 19', imageUrl: 'https://via.placeholder.com/150', rating: 7.3, likes: 190, genre: '액션' },
  { title: 'Movie 20', imageUrl: 'https://via.placeholder.com/150', rating: 9.2, likes: 310, genre: '모험' },
  { title: 'Movie 21', imageUrl: 'https://via.placeholder.com/150', rating: 7.4, likes: 230, genre: '애니메이션' },
  { title: 'Movie 22', imageUrl: 'https://via.placeholder.com/150', rating: 8.1, likes: 240, genre: '코미디' },
  { title: 'Movie 23', imageUrl: 'https://via.placeholder.com/150', rating: 7.7, likes: 250, genre: '범죄' },
  { title: 'Movie 24', imageUrl: 'https://via.placeholder.com/150', rating: 6.9, likes: 210, genre: '다큐멘터리' },
  { title: 'Movie 25', imageUrl: 'https://via.placeholder.com/150', rating: 8.5, likes: 260, genre: '드라마' },
  { title: 'Movie 26', imageUrl: 'https://via.placeholder.com/150', rating: 7.2, likes: 220, genre: '판타지' },
  { title: 'Movie 27', imageUrl: 'https://via.placeholder.com/150', rating: 9.0, likes: 300, genre: '역사' },
  { title: 'Movie 28', imageUrl: 'https://via.placeholder.com/150', rating: 6.8, likes: 180, genre: '공포' },
  { title: 'Movie 29', imageUrl: 'https://via.placeholder.com/150', rating: 7.5, likes: 190, genre: '음악' },
  { title: 'Movie 30', imageUrl: 'https://via.placeholder.com/150', rating: 8.3, likes: 220, genre: '미스터리' },
  { title: 'Movie 31', imageUrl: 'https://via.placeholder.com/150', rating: 7.0, likes: 180, genre: '로맨스' },
  { title: 'Movie 32', imageUrl: 'https://via.placeholder.com/150', rating: 8.6, likes: 310, genre: 'SF' },
  { title: 'Movie 33', imageUrl: 'https://via.placeholder.com/150', rating: 7.8, likes: 240, genre: 'TV 영화' },
  { title: 'Movie 34', imageUrl: 'https://via.placeholder.com/150', rating: 8.0, likes: 230, genre: '스릴러' },
  { title: 'Movie 35', imageUrl: 'https://via.placeholder.com/150', rating: 7.3, likes: 210, genre: '전쟁' },
  { title: 'Movie 36', imageUrl: 'https://via.placeholder.com/150', rating: 9.2, likes: 330, genre: '서부' },
  { title: 'Movie 37', imageUrl: 'https://via.placeholder.com/150', rating: 7.4, likes: 220, genre: '액션' },
  { title: 'Movie 38', imageUrl: 'https://via.placeholder.com/150', rating: 8.7, likes: 270, genre: '모험' },
  { title: 'Movie 39', imageUrl: 'https://via.placeholder.com/150', rating: 7.6, likes: 200, genre: '애니메이션' },
  { title: 'Movie 40', imageUrl: 'https://via.placeholder.com/150', rating: 8.4, likes: 260, genre: '코미디' },
];
